inherit_from: ./configs/Dynamic/Wild_SLAM_iPhone/wild_slam_iphone.yaml
scene: iphone_street

data:
  input_folder: ROOT_FOLDER_PLACEHOLDER/street

cam:
  fx: 1331.6123046875
  fy: 1331.6123046875
  cx: 956.61676025390625
  cy: 727.839599609375