inherit_from: ./configs/Dynamic/Wild_SLAM_iPhone/wild_slam_iphone.yaml
scene: iphone_tower

data:
  input_folder: ROOT_FOLDER_PLACEHOLDER/tower

cam:
  fx: 1338.494140625
  fy: 1338.494140625
  cx: 960.17327880859375
  cy: 730.55328369140625