inherit_from: ./configs/Dynamic/Wild_SLAM_Mocap/wild_slam_mocap.yaml
scene: crowd_demo

fast_mode: True
gui: True
mapping:
  online_plotting: True

data:
  input_folder: ROOT_FOLDER_PLACEHOLDER/scene1/crowd
  output: ./output/Wild_SLAM_Mocap_demo