inherit_from: ./configs/Dynamic/Wild_SLAM_Mocap/wild_slam_mocap.yaml
scene: table_tracking1

data:
  input_folder: ROOT_FOLDER_PLACEHOLDER/scene1/table_tracking1

cam: 
  fx: 647.9204711914062
  fy: 647.1183471679688